version: 2
jobs:
  tests:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem install bundler --conservative --version '~> 1.17'
      - run: bundle install
      - run: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - tests